/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTendersRouteImport } from './routes/_authenticated/tenders'
import { Route as AuthenticatedTenderConversionRouteImport } from './routes/_authenticated/tender-conversion'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRfqJihRouteImport } from './routes/_authenticated/rfq-jih'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReferenceLibraryRouteImport } from './routes/_authenticated/reference-library'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedMyWorkspaceRouteImport } from './routes/_authenticated/my-workspace'
import { Route as AuthenticatedLeadTenderInboxRouteImport } from './routes/_authenticated/lead-tender-inbox'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedDataImportRouteImport } from './routes/_authenticated/data-import'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedBoqRouteImport } from './routes/_authenticated/boq'
import { Route as AuthenticatedAwardQueueRouteImport } from './routes/_authenticated/award-queue'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAiAgentsRouteImport } from './routes/_authenticated/ai-agents'
import { Route as AuthenticatedAgentActivityRouteImport } from './routes/_authenticated/agent-activity'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedActionCenterRouteImport } from './routes/_authenticated/action-center'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedOpportunitiesIndexRouteImport } from './routes/_authenticated/opportunities.index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedOpportunitiesIdRouteImport } from './routes/_authenticated/opportunities.$id'
import { Route as AuthenticatedDataImportBatchIdRouteImport } from './routes/_authenticated/data-import.$batchId'
import { Route as AuthenticatedAccountsIdRouteImport } from './routes/_authenticated/accounts.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTendersRoute = AuthenticatedTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenderConversionRoute =
  AuthenticatedTenderConversionRouteImport.update({
    id: '/tender-conversion',
    path: '/tender-conversion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfqJihRoute = AuthenticatedRfqJihRouteImport.update({
  id: '/rfq-jih',
  path: '/rfq-jih',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferenceLibraryRoute =
  AuthenticatedReferenceLibraryRouteImport.update({
    id: '/reference-library',
    path: '/reference-library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyWorkspaceRoute =
  AuthenticatedMyWorkspaceRouteImport.update({
    id: '/my-workspace',
    path: '/my-workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadTenderInboxRoute =
  AuthenticatedLeadTenderInboxRouteImport.update({
    id: '/lead-tender-inbox',
    path: '/lead-tender-inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataImportRoute = AuthenticatedDataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoqRoute = AuthenticatedBoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAwardQueueRoute = AuthenticatedAwardQueueRouteImport.update({
  id: '/award-queue',
  path: '/award-queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAgentsRoute = AuthenticatedAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentActivityRoute =
  AuthenticatedAgentActivityRouteImport.update({
    id: '/agent-activity',
    path: '/agent-activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionCenterRoute =
  AuthenticatedActionCenterRouteImport.update({
    id: '/action-center',
    path: '/action-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOpportunitiesIndexRoute =
  AuthenticatedOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedOpportunitiesIdRoute =
  AuthenticatedOpportunitiesIdRouteImport.update({
    id: '/opportunities/$id',
    path: '/opportunities/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataImportBatchIdRoute =
  AuthenticatedDataImportBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedDataImportRoute,
  } as any)
const AuthenticatedAccountsIdRoute = AuthenticatedAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAccountsRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/action-center': typeof AuthenticatedActionCenterRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/ai-agents': typeof AuthenticatedAiAgentsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/award-queue': typeof AuthenticatedAwardQueueRoute
  '/boq': typeof AuthenticatedBoqRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/data-import': typeof AuthenticatedDataImportRouteWithChildren
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/lead-tender-inbox': typeof AuthenticatedLeadTenderInboxRoute
  '/my-workspace': typeof AuthenticatedMyWorkspaceRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reference-library': typeof AuthenticatedReferenceLibraryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rfq-jih': typeof AuthenticatedRfqJihRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tender-conversion': typeof AuthenticatedTenderConversionRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/data-import/$batchId': typeof AuthenticatedDataImportBatchIdRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/action-center': typeof AuthenticatedActionCenterRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/ai-agents': typeof AuthenticatedAiAgentsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/award-queue': typeof AuthenticatedAwardQueueRoute
  '/boq': typeof AuthenticatedBoqRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/data-import': typeof AuthenticatedDataImportRouteWithChildren
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/lead-tender-inbox': typeof AuthenticatedLeadTenderInboxRoute
  '/my-workspace': typeof AuthenticatedMyWorkspaceRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reference-library': typeof AuthenticatedReferenceLibraryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rfq-jih': typeof AuthenticatedRfqJihRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tender-conversion': typeof AuthenticatedTenderConversionRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/data-import/$batchId': typeof AuthenticatedDataImportBatchIdRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/opportunities': typeof AuthenticatedOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/action-center': typeof AuthenticatedActionCenterRoute
  '/_authenticated/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/_authenticated/ai-agents': typeof AuthenticatedAiAgentsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/award-queue': typeof AuthenticatedAwardQueueRoute
  '/_authenticated/boq': typeof AuthenticatedBoqRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/data-import': typeof AuthenticatedDataImportRouteWithChildren
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/lead-tender-inbox': typeof AuthenticatedLeadTenderInboxRoute
  '/_authenticated/my-workspace': typeof AuthenticatedMyWorkspaceRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/reference-library': typeof AuthenticatedReferenceLibraryRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rfq-jih': typeof AuthenticatedRfqJihRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/tender-conversion': typeof AuthenticatedTenderConversionRoute
  '/_authenticated/tenders': typeof AuthenticatedTendersRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/_authenticated/data-import/$batchId': typeof AuthenticatedDataImportBatchIdRoute
  '/_authenticated/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pending-approval'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/action-center'
    | '/admin-settings'
    | '/agent-activity'
    | '/ai-agents'
    | '/approvals'
    | '/award-queue'
    | '/boq'
    | '/command-center'
    | '/contacts'
    | '/data-import'
    | '/discovery'
    | '/follow-ups'
    | '/knowledge'
    | '/lead-tender-inbox'
    | '/my-workspace'
    | '/projects'
    | '/quotations'
    | '/reference-library'
    | '/reports'
    | '/rfq-jih'
    | '/settings'
    | '/targets'
    | '/team'
    | '/tender-conversion'
    | '/tenders'
    | '/vendors'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/accounts/$id'
    | '/data-import/$batchId'
    | '/opportunities/$id'
    | '/projects/$id'
    | '/accounts/'
    | '/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pending-approval'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/action-center'
    | '/admin-settings'
    | '/agent-activity'
    | '/ai-agents'
    | '/approvals'
    | '/award-queue'
    | '/boq'
    | '/command-center'
    | '/contacts'
    | '/data-import'
    | '/discovery'
    | '/follow-ups'
    | '/knowledge'
    | '/lead-tender-inbox'
    | '/my-workspace'
    | '/projects'
    | '/quotations'
    | '/reference-library'
    | '/reports'
    | '/rfq-jih'
    | '/settings'
    | '/targets'
    | '/team'
    | '/tender-conversion'
    | '/tenders'
    | '/vendors'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/accounts/$id'
    | '/data-import/$batchId'
    | '/opportunities/$id'
    | '/projects/$id'
    | '/accounts'
    | '/opportunities'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/pending-approval'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/accounts'
    | '/_authenticated/action-center'
    | '/_authenticated/admin-settings'
    | '/_authenticated/agent-activity'
    | '/_authenticated/ai-agents'
    | '/_authenticated/approvals'
    | '/_authenticated/award-queue'
    | '/_authenticated/boq'
    | '/_authenticated/command-center'
    | '/_authenticated/contacts'
    | '/_authenticated/data-import'
    | '/_authenticated/discovery'
    | '/_authenticated/follow-ups'
    | '/_authenticated/knowledge'
    | '/_authenticated/lead-tender-inbox'
    | '/_authenticated/my-workspace'
    | '/_authenticated/projects'
    | '/_authenticated/quotations'
    | '/_authenticated/reference-library'
    | '/_authenticated/reports'
    | '/_authenticated/rfq-jih'
    | '/_authenticated/settings'
    | '/_authenticated/targets'
    | '/_authenticated/team'
    | '/_authenticated/tender-conversion'
    | '/_authenticated/tenders'
    | '/_authenticated/vendors'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/accounts/$id'
    | '/_authenticated/data-import/$batchId'
    | '/_authenticated/opportunities/$id'
    | '/_authenticated/projects/$id'
    | '/_authenticated/accounts/'
    | '/_authenticated/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenders': {
      id: '/_authenticated/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AuthenticatedTendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tender-conversion': {
      id: '/_authenticated/tender-conversion'
      path: '/tender-conversion'
      fullPath: '/tender-conversion'
      preLoaderRoute: typeof AuthenticatedTenderConversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfq-jih': {
      id: '/_authenticated/rfq-jih'
      path: '/rfq-jih'
      fullPath: '/rfq-jih'
      preLoaderRoute: typeof AuthenticatedRfqJihRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reference-library': {
      id: '/_authenticated/reference-library'
      path: '/reference-library'
      fullPath: '/reference-library'
      preLoaderRoute: typeof AuthenticatedReferenceLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-workspace': {
      id: '/_authenticated/my-workspace'
      path: '/my-workspace'
      fullPath: '/my-workspace'
      preLoaderRoute: typeof AuthenticatedMyWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lead-tender-inbox': {
      id: '/_authenticated/lead-tender-inbox'
      path: '/lead-tender-inbox'
      fullPath: '/lead-tender-inbox'
      preLoaderRoute: typeof AuthenticatedLeadTenderInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-import': {
      id: '/_authenticated/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof AuthenticatedDataImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boq': {
      id: '/_authenticated/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof AuthenticatedBoqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/award-queue': {
      id: '/_authenticated/award-queue'
      path: '/award-queue'
      fullPath: '/award-queue'
      preLoaderRoute: typeof AuthenticatedAwardQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-agents': {
      id: '/_authenticated/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AuthenticatedAiAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-activity': {
      id: '/_authenticated/agent-activity'
      path: '/agent-activity'
      fullPath: '/agent-activity'
      preLoaderRoute: typeof AuthenticatedAgentActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-settings': {
      id: '/_authenticated/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action-center': {
      id: '/_authenticated/action-center'
      path: '/action-center'
      fullPath: '/action-center'
      preLoaderRoute: typeof AuthenticatedActionCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/opportunities/': {
      id: '/_authenticated/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/opportunities/$id': {
      id: '/_authenticated/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-import/$batchId': {
      id: '/_authenticated/data-import/$batchId'
      path: '/$batchId'
      fullPath: '/data-import/$batchId'
      preLoaderRoute: typeof AuthenticatedDataImportBatchIdRouteImport
      parentRoute: typeof AuthenticatedDataImportRoute
    }
    '/_authenticated/accounts/$id': {
      id: '/_authenticated/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountsIdRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsIdRoute: typeof AuthenticatedAccountsIdRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsIdRoute: AuthenticatedAccountsIdRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedDataImportRouteChildren {
  AuthenticatedDataImportBatchIdRoute: typeof AuthenticatedDataImportBatchIdRoute
}

const AuthenticatedDataImportRouteChildren: AuthenticatedDataImportRouteChildren =
  {
    AuthenticatedDataImportBatchIdRoute: AuthenticatedDataImportBatchIdRoute,
  }

const AuthenticatedDataImportRouteWithChildren =
  AuthenticatedDataImportRoute._addFileChildren(
    AuthenticatedDataImportRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedActionCenterRoute: typeof AuthenticatedActionCenterRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAgentActivityRoute: typeof AuthenticatedAgentActivityRoute
  AuthenticatedAiAgentsRoute: typeof AuthenticatedAiAgentsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAwardQueueRoute: typeof AuthenticatedAwardQueueRoute
  AuthenticatedBoqRoute: typeof AuthenticatedBoqRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDataImportRoute: typeof AuthenticatedDataImportRouteWithChildren
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadTenderInboxRoute: typeof AuthenticatedLeadTenderInboxRoute
  AuthenticatedMyWorkspaceRoute: typeof AuthenticatedMyWorkspaceRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedReferenceLibraryRoute: typeof AuthenticatedReferenceLibraryRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRfqJihRoute: typeof AuthenticatedRfqJihRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTenderConversionRoute: typeof AuthenticatedTenderConversionRoute
  AuthenticatedTendersRoute: typeof AuthenticatedTendersRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedOpportunitiesIdRoute: typeof AuthenticatedOpportunitiesIdRoute
  AuthenticatedOpportunitiesIndexRoute: typeof AuthenticatedOpportunitiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedActionCenterRoute: AuthenticatedActionCenterRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAgentActivityRoute: AuthenticatedAgentActivityRoute,
  AuthenticatedAiAgentsRoute: AuthenticatedAiAgentsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAwardQueueRoute: AuthenticatedAwardQueueRoute,
  AuthenticatedBoqRoute: AuthenticatedBoqRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDataImportRoute: AuthenticatedDataImportRouteWithChildren,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadTenderInboxRoute: AuthenticatedLeadTenderInboxRoute,
  AuthenticatedMyWorkspaceRoute: AuthenticatedMyWorkspaceRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedReferenceLibraryRoute: AuthenticatedReferenceLibraryRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRfqJihRoute: AuthenticatedRfqJihRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTenderConversionRoute: AuthenticatedTenderConversionRoute,
  AuthenticatedTendersRoute: AuthenticatedTendersRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedOpportunitiesIdRoute: AuthenticatedOpportunitiesIdRoute,
  AuthenticatedOpportunitiesIndexRoute: AuthenticatedOpportunitiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
